export const TICK_RATE = 10;
export const TICK_MS = 1000 / TICK_RATE;
export const TILE_SIZE = 32;
export const CHUNK_SIZE = 16;
export const VIEW_RANGE_CHUNKS = 2;
export const PLAYER_SPEED = 4; // tiles per second
export const INVENTORY_SIZE = 28;
export const EQUIP_SLOTS = 10;
export const MAX_PARTY_SIZE = 5;
export const PARTY_XP_RANGE = 15;
export const PARTY_XP_BONUS = 0.1;
