import { ItemCategory, EquipSlot, Rarity, type ItemDef } from "../types/item.js";
import { SkillName } from "../types/skill.js";

export const ITEMS: Record<string, ItemDef> = {
  // --- Weapons ---
  wooden_sword: {
    id: "wooden_sword",
    name: "Wooden Sword",
    description: "A basic training sword.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 5 },
    rarity: Rarity.COMMON,
    value: 10,
  },
  bronze_sword: {
    id: "bronze_sword",
    name: "Bronze Sword",
    description: "A sturdy bronze blade.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 12 },
    rarity: Rarity.COMMON,
    levelReq: { [SkillName.MELEE]: 10 },
    value: 50,
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    description: "A reliable iron sword.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 22 },
    rarity: Rarity.UNCOMMON,
    levelReq: { [SkillName.MELEE]: 25 },
    value: 200,
  },
  steel_sword: {
    id: "steel_sword",
    name: "Steel Sword",
    description: "A finely forged steel blade.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 38 },
    rarity: Rarity.RARE,
    levelReq: { [SkillName.MELEE]: 20 },
    value: 800,
  },
  wooden_bow: {
    id: "wooden_bow",
    name: "Wooden Bow",
    description: "A simple shortbow.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { rangedAttack: 8 },
    rarity: Rarity.COMMON,
    value: 15,
  },

  // --- Armor ---
  leather_cap: {
    id: "leather_cap",
    name: "Leather Cap",
    description: "Basic head protection.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.HEAD,
    stats: { defense: 3 },
    rarity: Rarity.COMMON,
    value: 20,
  },
  leather_tunic: {
    id: "leather_tunic",
    name: "Leather Tunic",
    description: "A simple leather chest piece.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.CHEST,
    stats: { defense: 8 },
    rarity: Rarity.COMMON,
    value: 40,
  },
  leather_pants: {
    id: "leather_pants",
    name: "Leather Pants",
    description: "Basic leg armor.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.LEGS,
    stats: { defense: 5 },
    rarity: Rarity.COMMON,
    value: 30,
  },
  leather_boots: {
    id: "leather_boots",
    name: "Leather Boots",
    description: "Simple leather footwear.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.FEET,
    stats: { defense: 2 },
    rarity: Rarity.COMMON,
    value: 15,
  },
  bronze_helm: {
    id: "bronze_helm",
    name: "Bronze Helm",
    description: "A heavy bronze helmet.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.HEAD,
    stats: { defense: 8 },
    rarity: Rarity.COMMON,
    levelReq: { [SkillName.DEFENSE]: 10 },
    value: 60,
  },
  bronze_platebody: {
    id: "bronze_platebody",
    name: "Bronze Platebody",
    description: "A bronze chest plate.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.CHEST,
    stats: { defense: 18 },
    rarity: Rarity.COMMON,
    levelReq: { [SkillName.DEFENSE]: 10 },
    value: 120,
  },
  wooden_shield: {
    id: "wooden_shield",
    name: "Wooden Shield",
    description: "A basic wooden shield.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.SHIELD,
    stats: { defense: 5 },
    rarity: Rarity.COMMON,
    value: 25,
  },

  // --- Tools ---
  fishing_rod: {
    id: "fishing_rod",
    name: "Fishing Rod",
    description: "A basic fishing rod.",
    category: ItemCategory.TOOL,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    rarity: Rarity.COMMON,
    value: 20,
  },
  bronze_pickaxe: {
    id: "bronze_pickaxe",
    name: "Bronze Pickaxe",
    description: "A basic mining tool.",
    category: ItemCategory.TOOL,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    rarity: Rarity.COMMON,
    value: 25,
  },
  bronze_axe: {
    id: "bronze_axe",
    name: "Bronze Axe",
    description: "A basic woodcutting axe.",
    category: ItemCategory.TOOL,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    rarity: Rarity.COMMON,
    value: 25,
  },

  // --- Food / Consumables ---
  raw_shrimp: {
    id: "raw_shrimp",
    name: "Raw Shrimp",
    description: "A freshly caught shrimp. Can be cooked.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 2,
  },
  cooked_shrimp: {
    id: "cooked_shrimp",
    name: "Cooked Shrimp",
    description: "A delicious cooked shrimp.",
    category: ItemCategory.CONSUMABLE,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
    healAmount: 30,
  },
  raw_trout: {
    id: "raw_trout",
    name: "Raw Trout",
    description: "A fresh trout. Can be cooked.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 8,
  },
  cooked_trout: {
    id: "cooked_trout",
    name: "Cooked Trout",
    description: "A nicely grilled trout.",
    category: ItemCategory.CONSUMABLE,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 15,
    healAmount: 70,
  },
  bread: {
    id: "bread",
    name: "Bread",
    description: "A loaf of bread.",
    category: ItemCategory.CONSUMABLE,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
    healAmount: 50,
  },

  // --- Materials ---
  copper_ore: {
    id: "copper_ore",
    name: "Copper Ore",
    description: "A chunk of copper ore.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
  },
  tin_ore: {
    id: "tin_ore",
    name: "Tin Ore",
    description: "A chunk of tin ore.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
  },
  bronze_bar: {
    id: "bronze_bar",
    name: "Bronze Bar",
    description: "A bar of bronze.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 15,
  },
  logs: {
    id: "logs",
    name: "Logs",
    description: "A bundle of logs.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 3,
  },
  herb: {
    id: "herb",
    name: "Herb",
    description: "A mysterious herb.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 8,
  },

  // --- Boss Loot ---
  chieftain_axe: {
    id: "chieftain_axe",
    name: "Chieftain's Axe",
    description: "A brutal axe wielded by the Goblin Chieftain.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 32 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.MELEE]: 15 },
    value: 500,
  },
  chieftain_helm: {
    id: "chieftain_helm",
    name: "Chieftain's Helm",
    description: "A horned helmet taken from the Goblin Chieftain.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.HEAD,
    stats: { defense: 14 },
    rarity: Rarity.RARE,
    levelReq: { [SkillName.DEFENSE]: 15 },
    value: 350,
  },
  lich_staff: {
    id: "lich_staff",
    name: "Staff of the Lich",
    description: "A dark staff pulsing with necrotic energy.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 45 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.MELEE]: 20 },
    value: 900,
  },
  lich_robe: {
    id: "lich_robe",
    name: "Lich King's Robe",
    description: "Dark robes imbued with unholy power.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.CHEST,
    stats: { defense: 25, hp: 20 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.DEFENSE]: 20 },
    value: 800,
  },
  bone_shield: {
    id: "bone_shield",
    name: "Bone Shield",
    description: "A shield made from the bones of the fallen.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.SHIELD,
    stats: { defense: 18 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.DEFENSE]: 16 },
    value: 600,
  },

  // --- New Materials ---
  iron_ore: { id: "iron_ore", name: "Iron Ore", description: "Rough iron ore from the highlands.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.COMMON, value: 12 },
  fire_ruby: { id: "fire_ruby", name: "Fire Ruby", description: "A gem pulsing with inner heat.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.UNCOMMON, value: 50 },
  wolf_pelt: { id: "wolf_pelt", name: "Wolf Pelt", description: "Thick frost wolf fur.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.COMMON, value: 15 },
  frost_shard: { id: "frost_shard", name: "Frost Shard", description: "A shard of living ice.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.UNCOMMON, value: 25 },
  yeti_fur: { id: "yeti_fur", name: "Yeti Fur", description: "Incredibly warm and tough.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.UNCOMMON, value: 30 },
  crystal_core: { id: "crystal_core", name: "Crystal Core", description: "Resonating crystalline energy.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.RARE, value: 60 },
  dragon_scale: { id: "dragon_scale", name: "Dragon Scale", description: "Nearly indestructible scale.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.EPIC, value: 80 },

  // --- New Equipment ---
  dragon_slayer: { id: "dragon_slayer", name: "Dragon Slayer", description: "A legendary blade forged to slay dragons.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 55 }, rarity: Rarity.EPIC, levelReq: { [SkillName.MELEE]: 28 }, value: 1500 },
  drake_plate: { id: "drake_plate", name: "Drake Platebody", description: "Armor crafted from drake scales. Incredibly durable.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.CHEST, stats: { defense: 35, hp: 30 }, rarity: Rarity.EPIC, levelReq: { [SkillName.DEFENSE]: 25 }, value: 1200 },

  // --- Currency ---
  gold_coins: {
    id: "gold_coins",
    name: "Gold Coins",
    description: "Shiny gold coins.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 999999,
    rarity: Rarity.COMMON,
    value: 1,
  },

  // --- Tier 2 Weapons ---
  iron_axe: { id: "iron_axe", name: "Iron Axe", description: "A sturdy axe forged from iron.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 15 }, rarity: Rarity.COMMON, levelReq: { [SkillName.MELEE]: 8 }, value: 80 },
  steel_mace: { id: "steel_mace", name: "Steel Mace", description: "A heavy mace that packs a punch.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 20 }, rarity: Rarity.UNCOMMON, levelReq: { [SkillName.MELEE]: 15 }, value: 200 },
  crystal_staff: { id: "crystal_staff", name: "Crystal Staff", description: "A staff imbued with crystalline energy.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 18, rangedAttack: 12 }, rarity: Rarity.RARE, levelReq: { [SkillName.MELEE]: 12 }, value: 400 },
  frost_blade: { id: "frost_blade", name: "Frost Blade", description: "A sword cold to the touch, forged in the Frozen Wastes.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 28 }, rarity: Rarity.RARE, levelReq: { [SkillName.MELEE]: 18 }, value: 600 },
  inferno_axe: { id: "inferno_axe", name: "Inferno Axe", description: "An axe that burns with eternal flame.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 35 }, rarity: Rarity.EPIC, levelReq: { [SkillName.MELEE]: 22 }, value: 1000 },
  shadow_dagger: { id: "shadow_dagger", name: "Shadow Dagger", description: "A dagger that seems to bend light around it.", category: ItemCategory.WEAPON, stackable: false, maxStack: 1, equipSlot: EquipSlot.WEAPON, stats: { attack: 25, speed: 2 }, rarity: Rarity.EPIC, levelReq: { [SkillName.MELEE]: 20 }, value: 900 },

  // --- Tier 2 Armor ---
  chain_legs: { id: "chain_legs", name: "Chain Leggings", description: "Linked chain protects the legs.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.LEGS, stats: { defense: 8 }, rarity: Rarity.COMMON, levelReq: { [SkillName.DEFENSE]: 5 }, value: 60 },
  iron_boots: { id: "iron_boots", name: "Iron Boots", description: "Heavy but protective iron boots.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.FEET, stats: { defense: 5 }, rarity: Rarity.COMMON, levelReq: { [SkillName.DEFENSE]: 5 }, value: 50 },
  steel_helm: { id: "steel_helm", name: "Steel Helm", description: "A full steel helmet with cheek guards.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.HEAD, stats: { defense: 12 }, rarity: Rarity.UNCOMMON, levelReq: { [SkillName.DEFENSE]: 12 }, value: 200 },
  steel_plate: { id: "steel_plate", name: "Steel Platebody", description: "Full plate armor of tempered steel.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.CHEST, stats: { defense: 22 }, rarity: Rarity.UNCOMMON, levelReq: { [SkillName.DEFENSE]: 15 }, value: 400 },
  crystal_shield: { id: "crystal_shield", name: "Crystal Shield", description: "A translucent shield humming with energy.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.SHIELD, stats: { defense: 15 }, rarity: Rarity.RARE, levelReq: { [SkillName.DEFENSE]: 15 }, value: 500 },
  frost_armor: { id: "frost_armor", name: "Frost Armor", description: "Armor forged from enchanted ice that never melts.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.CHEST, stats: { defense: 28, hp: 15 }, rarity: Rarity.RARE, levelReq: { [SkillName.DEFENSE]: 20 }, value: 800 },
  shadow_cloak: { id: "shadow_cloak", name: "Shadow Cloak", description: "A cloak woven from shadows. Grants swiftness.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.CHEST, stats: { defense: 10, speed: 3 }, rarity: Rarity.EPIC, levelReq: { [SkillName.DEFENSE]: 18 }, value: 750 },
  dragon_helm: { id: "dragon_helm", name: "Dragon Helm", description: "A fearsome helm crafted from dragon bone.", category: ItemCategory.ARMOR, stackable: false, maxStack: 1, equipSlot: EquipSlot.HEAD, stats: { defense: 20, hp: 25 }, rarity: Rarity.EPIC, levelReq: { [SkillName.DEFENSE]: 25 }, value: 1200 },

  // --- Better Consumables ---
  cooked_salmon: { id: "cooked_salmon", name: "Cooked Salmon", description: "A hearty salmon fillet.", category: ItemCategory.CONSUMABLE, stackable: true, maxStack: 99, rarity: Rarity.COMMON, value: 15, healAmount: 40 },
  meat_pie: { id: "meat_pie", name: "Meat Pie", description: "A savory pie packed with protein.", category: ItemCategory.CONSUMABLE, stackable: true, maxStack: 99, rarity: Rarity.UNCOMMON, value: 30, healAmount: 60 },
  elixir_of_life: { id: "elixir_of_life", name: "Elixir of Life", description: "A powerful healing potion brewed by alchemists.", category: ItemCategory.CONSUMABLE, stackable: true, maxStack: 20, rarity: Rarity.RARE, value: 100, healAmount: 120 },
  golden_apple: { id: "golden_apple", name: "Golden Apple", description: "A mythical fruit said to grant vitality.", category: ItemCategory.CONSUMABLE, stackable: true, maxStack: 10, rarity: Rarity.EPIC, value: 500, healAmount: 200 },

  // --- Crafting Materials ---
  steel_bar: { id: "steel_bar", name: "Steel Bar", description: "A bar of refined steel.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.UNCOMMON, value: 25 },
  mithril_ore: { id: "mithril_ore", name: "Mithril Ore", description: "A rare ore with a blue sheen.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.RARE, value: 50 },
  enchanted_gem: { id: "enchanted_gem", name: "Enchanted Gem", description: "A gem pulsing with arcane energy.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.RARE, value: 75 },
  ancient_rune: { id: "ancient_rune", name: "Ancient Rune", description: "A rune inscribed with forgotten magic.", category: ItemCategory.MATERIAL, stackable: true, maxStack: 99, rarity: Rarity.EPIC, value: 150 },
};

export function getItem(id: string): ItemDef | undefined {
  return ITEMS[id];
}
