import { ItemCategory, EquipSlot, Rarity, type ItemDef } from "../types/item.js";
import { SkillName } from "../types/skill.js";

export const ITEMS: Record<string, ItemDef> = {
  // --- Weapons ---
  wooden_sword: {
    id: "wooden_sword",
    name: "Wooden Sword",
    description: "A basic training sword.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 5 },
    rarity: Rarity.COMMON,
    value: 10,
  },
  bronze_sword: {
    id: "bronze_sword",
    name: "Bronze Sword",
    description: "A sturdy bronze blade.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 12 },
    rarity: Rarity.COMMON,
    levelReq: { [SkillName.MELEE]: 10 },
    value: 50,
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    description: "A reliable iron sword.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 22 },
    rarity: Rarity.UNCOMMON,
    levelReq: { [SkillName.MELEE]: 25 },
    value: 200,
  },
  steel_sword: {
    id: "steel_sword",
    name: "Steel Sword",
    description: "A finely forged steel blade.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 38 },
    rarity: Rarity.RARE,
    levelReq: { [SkillName.MELEE]: 45 },
    value: 800,
  },
  wooden_bow: {
    id: "wooden_bow",
    name: "Wooden Bow",
    description: "A simple shortbow.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { rangedAttack: 8 },
    rarity: Rarity.COMMON,
    value: 15,
  },

  // --- Armor ---
  leather_cap: {
    id: "leather_cap",
    name: "Leather Cap",
    description: "Basic head protection.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.HEAD,
    stats: { defense: 3 },
    rarity: Rarity.COMMON,
    value: 20,
  },
  leather_tunic: {
    id: "leather_tunic",
    name: "Leather Tunic",
    description: "A simple leather chest piece.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.CHEST,
    stats: { defense: 8 },
    rarity: Rarity.COMMON,
    value: 40,
  },
  leather_pants: {
    id: "leather_pants",
    name: "Leather Pants",
    description: "Basic leg armor.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.LEGS,
    stats: { defense: 5 },
    rarity: Rarity.COMMON,
    value: 30,
  },
  leather_boots: {
    id: "leather_boots",
    name: "Leather Boots",
    description: "Simple leather footwear.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.FEET,
    stats: { defense: 2 },
    rarity: Rarity.COMMON,
    value: 15,
  },
  bronze_helm: {
    id: "bronze_helm",
    name: "Bronze Helm",
    description: "A heavy bronze helmet.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.HEAD,
    stats: { defense: 8 },
    rarity: Rarity.COMMON,
    levelReq: { [SkillName.DEFENSE]: 10 },
    value: 60,
  },
  bronze_platebody: {
    id: "bronze_platebody",
    name: "Bronze Platebody",
    description: "A bronze chest plate.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.CHEST,
    stats: { defense: 18 },
    rarity: Rarity.COMMON,
    levelReq: { [SkillName.DEFENSE]: 10 },
    value: 120,
  },
  wooden_shield: {
    id: "wooden_shield",
    name: "Wooden Shield",
    description: "A basic wooden shield.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.SHIELD,
    stats: { defense: 5 },
    rarity: Rarity.COMMON,
    value: 25,
  },

  // --- Tools ---
  fishing_rod: {
    id: "fishing_rod",
    name: "Fishing Rod",
    description: "A basic fishing rod.",
    category: ItemCategory.TOOL,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    rarity: Rarity.COMMON,
    value: 20,
  },
  bronze_pickaxe: {
    id: "bronze_pickaxe",
    name: "Bronze Pickaxe",
    description: "A basic mining tool.",
    category: ItemCategory.TOOL,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    rarity: Rarity.COMMON,
    value: 25,
  },
  bronze_axe: {
    id: "bronze_axe",
    name: "Bronze Axe",
    description: "A basic woodcutting axe.",
    category: ItemCategory.TOOL,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    rarity: Rarity.COMMON,
    value: 25,
  },

  // --- Food / Consumables ---
  raw_shrimp: {
    id: "raw_shrimp",
    name: "Raw Shrimp",
    description: "A freshly caught shrimp. Can be cooked.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 2,
  },
  cooked_shrimp: {
    id: "cooked_shrimp",
    name: "Cooked Shrimp",
    description: "A delicious cooked shrimp.",
    category: ItemCategory.CONSUMABLE,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
    healAmount: 30,
  },
  raw_trout: {
    id: "raw_trout",
    name: "Raw Trout",
    description: "A fresh trout. Can be cooked.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 8,
  },
  cooked_trout: {
    id: "cooked_trout",
    name: "Cooked Trout",
    description: "A nicely grilled trout.",
    category: ItemCategory.CONSUMABLE,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 15,
    healAmount: 70,
  },
  bread: {
    id: "bread",
    name: "Bread",
    description: "A loaf of bread.",
    category: ItemCategory.CONSUMABLE,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
    healAmount: 50,
  },

  // --- Materials ---
  copper_ore: {
    id: "copper_ore",
    name: "Copper Ore",
    description: "A chunk of copper ore.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
  },
  tin_ore: {
    id: "tin_ore",
    name: "Tin Ore",
    description: "A chunk of tin ore.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 5,
  },
  bronze_bar: {
    id: "bronze_bar",
    name: "Bronze Bar",
    description: "A bar of bronze.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 15,
  },
  logs: {
    id: "logs",
    name: "Logs",
    description: "A bundle of logs.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 3,
  },
  herb: {
    id: "herb",
    name: "Herb",
    description: "A mysterious herb.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 99,
    rarity: Rarity.COMMON,
    value: 8,
  },

  // --- Boss Loot ---
  chieftain_axe: {
    id: "chieftain_axe",
    name: "Chieftain's Axe",
    description: "A brutal axe wielded by the Goblin Chieftain.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 32 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.MELEE]: 15 },
    value: 500,
  },
  chieftain_helm: {
    id: "chieftain_helm",
    name: "Chieftain's Helm",
    description: "A horned helmet taken from the Goblin Chieftain.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.HEAD,
    stats: { defense: 14 },
    rarity: Rarity.RARE,
    levelReq: { [SkillName.DEFENSE]: 15 },
    value: 350,
  },
  lich_staff: {
    id: "lich_staff",
    name: "Staff of the Lich",
    description: "A dark staff pulsing with necrotic energy.",
    category: ItemCategory.WEAPON,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.WEAPON,
    stats: { attack: 45 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.MELEE]: 20 },
    value: 900,
  },
  lich_robe: {
    id: "lich_robe",
    name: "Lich King's Robe",
    description: "Dark robes imbued with unholy power.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.CHEST,
    stats: { defense: 25, hp: 20 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.DEFENSE]: 20 },
    value: 800,
  },
  bone_shield: {
    id: "bone_shield",
    name: "Bone Shield",
    description: "A shield made from the bones of the fallen.",
    category: ItemCategory.ARMOR,
    stackable: false,
    maxStack: 1,
    equipSlot: EquipSlot.SHIELD,
    stats: { defense: 18 },
    rarity: Rarity.EPIC,
    levelReq: { [SkillName.DEFENSE]: 16 },
    value: 600,
  },

  // --- Currency ---
  gold_coins: {
    id: "gold_coins",
    name: "Gold Coins",
    description: "Shiny gold coins.",
    category: ItemCategory.MATERIAL,
    stackable: true,
    maxStack: 999999,
    rarity: Rarity.COMMON,
    value: 1,
  },
};

export function getItem(id: string): ItemDef | undefined {
  return ITEMS[id];
}
