import type { MobDef } from "../types/mob.js";

export const MOBS: Record<string, MobDef> = {
  chicken: {
    id: "chicken",
    name: "Chicken",
    level: 1,
    maxHp: 15,
    attack: 1,
    defense: 1,
    attackSpeed: 6,
    aggroRange: 0,
    chaseRange: 0,
    respawnTicks: 300,
    xpReward: 10,
    lootTable: [
      { itemId: "raw_shrimp", quantity: 1, chance: 0.5 },
    ],
  },
  goblin: {
    id: "goblin",
    name: "Goblin",
    level: 3,
    maxHp: 40,
    attack: 5,
    defense: 3,
    attackSpeed: 5,
    aggroRange: 4,
    chaseRange: 8,
    respawnTicks: 500,
    xpReward: 25,
    lootTable: [
      { itemId: "gold_coins", quantity: 5, chance: 0.8 },
      { itemId: "bronze_sword", quantity: 1, chance: 0.05 },
    ],
  },
  cow: {
    id: "cow",
    name: "Cow",
    level: 5,
    maxHp: 80,
    attack: 3,
    defense: 5,
    attackSpeed: 6,
    aggroRange: 0,
    chaseRange: 0,
    respawnTicks: 500,
    xpReward: 35,
    lootTable: [
      { itemId: "leather_tunic", quantity: 1, chance: 0.1 },
    ],
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    level: 10,
    maxHp: 120,
    attack: 12,
    defense: 8,
    attackSpeed: 4,
    aggroRange: 5,
    chaseRange: 10,
    respawnTicks: 600,
    xpReward: 60,
    lootTable: [
      { itemId: "gold_coins", quantity: 15, chance: 0.7 },
      { itemId: "iron_sword", quantity: 1, chance: 0.03 },
      { itemId: "bronze_helm", quantity: 1, chance: 0.05 },
    ],
  },
  forest_spider: {
    id: "forest_spider",
    name: "Forest Spider",
    level: 7,
    maxHp: 70,
    attack: 9,
    defense: 4,
    attackSpeed: 3,
    aggroRange: 3,
    chaseRange: 6,
    respawnTicks: 450,
    xpReward: 45,
    lootTable: [
      { itemId: "herb", quantity: 1, chance: 0.3 },
    ],
  },
};
