import type { MobDef } from "../types/mob.js";

export const MOBS: Record<string, MobDef> = {
  chicken: {
    id: "chicken",
    name: "Chicken",
    level: 1,
    maxHp: 15,
    attack: 1,
    defense: 1,
    attackSpeed: 6,
    aggroRange: 0,
    chaseRange: 0,
    respawnTicks: 300,
    xpReward: 10,
    lootTable: [
      { itemId: "raw_shrimp", quantity: 1, chance: 0.5 },
    ],
  },
  goblin: {
    id: "goblin",
    name: "Goblin",
    level: 3,
    maxHp: 40,
    attack: 5,
    defense: 3,
    attackSpeed: 5,
    aggroRange: 4,
    chaseRange: 8,
    respawnTicks: 500,
    xpReward: 25,
    lootTable: [
      { itemId: "gold_coins", quantity: 5, chance: 0.8 },
      { itemId: "bronze_sword", quantity: 1, chance: 0.05 },
    ],
  },
  cow: {
    id: "cow",
    name: "Cow",
    level: 5,
    maxHp: 80,
    attack: 3,
    defense: 5,
    attackSpeed: 6,
    aggroRange: 0,
    chaseRange: 0,
    respawnTicks: 500,
    xpReward: 35,
    lootTable: [
      { itemId: "leather_tunic", quantity: 1, chance: 0.1 },
    ],
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    level: 10,
    maxHp: 120,
    attack: 12,
    defense: 8,
    attackSpeed: 4,
    aggroRange: 5,
    chaseRange: 10,
    respawnTicks: 600,
    xpReward: 60,
    lootTable: [
      { itemId: "gold_coins", quantity: 15, chance: 0.7 },
      { itemId: "iron_sword", quantity: 1, chance: 0.03 },
      { itemId: "bronze_helm", quantity: 1, chance: 0.05 },
    ],
  },
  forest_spider: {
    id: "forest_spider",
    name: "Forest Spider",
    level: 7,
    maxHp: 70,
    attack: 9,
    defense: 4,
    attackSpeed: 3,
    aggroRange: 3,
    chaseRange: 6,
    respawnTicks: 450,
    xpReward: 45,
    lootTable: [
      { itemId: "herb", quantity: 1, chance: 0.3 },
    ],
  },

  // --- Dungeon Mobs ---
  goblin_sentry: {
    id: "goblin_sentry",
    name: "Goblin Sentry",
    level: 5,
    maxHp: 60,
    attack: 7,
    defense: 4,
    attackSpeed: 5,
    aggroRange: 5,
    chaseRange: 15,
    respawnTicks: 9999,
    xpReward: 40,
    lootTable: [
      { itemId: "gold_coins", quantity: 8, chance: 0.9 },
    ],
  },
  goblin_warrior: {
    id: "goblin_warrior",
    name: "Goblin Warrior",
    level: 7,
    maxHp: 80,
    attack: 10,
    defense: 6,
    attackSpeed: 4,
    aggroRange: 5,
    chaseRange: 15,
    respawnTicks: 9999,
    xpReward: 55,
    lootTable: [
      { itemId: "gold_coins", quantity: 12, chance: 0.9 },
      { itemId: "bronze_sword", quantity: 1, chance: 0.1 },
    ],
  },
  goblin_mage: {
    id: "goblin_mage",
    name: "Goblin Mage",
    level: 9,
    maxHp: 60,
    attack: 14,
    defense: 3,
    attackSpeed: 5,
    aggroRange: 6,
    chaseRange: 15,
    respawnTicks: 9999,
    xpReward: 65,
    lootTable: [
      { itemId: "herb", quantity: 2, chance: 0.5 },
    ],
  },
  goblin_chieftain: {
    id: "goblin_chieftain",
    name: "Goblin Chieftain",
    level: 15,
    maxHp: 500,
    attack: 20,
    defense: 15,
    attackSpeed: 4,
    aggroRange: 8,
    chaseRange: 999,
    respawnTicks: 9999,
    xpReward: 300,
    isBoss: true,
    bossAbilities: [
      { id: "war_cry", name: "War Cry", damage: 0, radius: 0, cooldownTicks: 50, telegraphTicks: 0 },
      { id: "ground_slam", name: "Ground Slam", damage: 15, radius: 3, cooldownTicks: 80, telegraphTicks: 10 },
    ],
    lootTable: [
      { itemId: "chieftain_axe", quantity: 1, chance: 0.3 },
      { itemId: "chieftain_helm", quantity: 1, chance: 0.4 },
      { itemId: "gold_coins", quantity: 50, chance: 1.0 },
    ],
  },
  skeleton_soldier: {
    id: "skeleton_soldier",
    name: "Skeleton Soldier",
    level: 12,
    maxHp: 150,
    attack: 14,
    defense: 10,
    attackSpeed: 4,
    aggroRange: 5,
    chaseRange: 15,
    respawnTicks: 9999,
    xpReward: 75,
    lootTable: [
      { itemId: "gold_coins", quantity: 20, chance: 0.8 },
    ],
  },
  bone_archer: {
    id: "bone_archer",
    name: "Bone Archer",
    level: 12,
    maxHp: 100,
    attack: 16,
    defense: 5,
    attackSpeed: 5,
    aggroRange: 7,
    chaseRange: 15,
    respawnTicks: 9999,
    xpReward: 70,
    lootTable: [
      { itemId: "wooden_bow", quantity: 1, chance: 0.1 },
    ],
  },
  dark_cultist: {
    id: "dark_cultist",
    name: "Dark Cultist",
    level: 14,
    maxHp: 180,
    attack: 18,
    defense: 8,
    attackSpeed: 5,
    aggroRange: 6,
    chaseRange: 15,
    respawnTicks: 9999,
    xpReward: 90,
    lootTable: [
      { itemId: "herb", quantity: 3, chance: 0.6 },
    ],
  },
  bone_golem: {
    id: "bone_golem",
    name: "Bone Golem",
    level: 16,
    maxHp: 250,
    attack: 15,
    defense: 20,
    attackSpeed: 6,
    aggroRange: 4,
    chaseRange: 12,
    respawnTicks: 9999,
    xpReward: 110,
    lootTable: [
      { itemId: "gold_coins", quantity: 30, chance: 0.9 },
      { itemId: "bone_shield", quantity: 1, chance: 0.08 },
    ],
  },
  lich_king: {
    id: "lich_king",
    name: "Lich King",
    level: 20,
    maxHp: 800,
    attack: 25,
    defense: 20,
    attackSpeed: 4,
    aggroRange: 10,
    chaseRange: 999,
    respawnTicks: 9999,
    xpReward: 500,
    isBoss: true,
    bossAbilities: [
      { id: "soul_drain", name: "Soul Drain", damage: 20, radius: 4, cooldownTicks: 60, telegraphTicks: 8 },
      { id: "death_gaze", name: "Death Gaze", damage: 40, radius: 0, cooldownTicks: 100, telegraphTicks: 15 },
    ],
    lootTable: [
      { itemId: "lich_staff", quantity: 1, chance: 0.25 },
      { itemId: "lich_robe", quantity: 1, chance: 0.3 },
      { itemId: "gold_coins", quantity: 100, chance: 1.0 },
    ],
  },

  // --- Scorched Highlands Mobs ---
  fire_imp: { id: "fire_imp", name: "Fire Imp", level: 12, maxHp: 130, attack: 14, defense: 6, attackSpeed: 3, aggroRange: 4, chaseRange: 8, respawnTicks: 400, xpReward: 65, lootTable: [{ itemId: "gold_coins", quantity: 10, chance: 0.8 }, { itemId: "herb", quantity: 1, chance: 0.2 }] },
  lava_beetle: { id: "lava_beetle", name: "Lava Beetle", level: 14, maxHp: 160, attack: 16, defense: 12, attackSpeed: 6, aggroRange: 3, chaseRange: 6, respawnTicks: 500, xpReward: 80, lootTable: [{ itemId: "gold_coins", quantity: 15, chance: 0.7 }, { itemId: "iron_ore", quantity: 1, chance: 0.25 }] },
  scorched_warrior: { id: "scorched_warrior", name: "Scorched Warrior", level: 16, maxHp: 200, attack: 20, defense: 14, attackSpeed: 4, aggroRange: 5, chaseRange: 10, respawnTicks: 500, xpReward: 100, lootTable: [{ itemId: "gold_coins", quantity: 20, chance: 0.8 }, { itemId: "steel_sword", quantity: 1, chance: 0.03 }] },
  magma_elemental: { id: "magma_elemental", name: "Magma Elemental", level: 18, maxHp: 250, attack: 22, defense: 10, attackSpeed: 5, aggroRange: 5, chaseRange: 10, respawnTicks: 600, xpReward: 120, lootTable: [{ itemId: "gold_coins", quantity: 25, chance: 0.9 }, { itemId: "fire_ruby", quantity: 1, chance: 0.1 }] },

  // --- Frozen Wastes Mobs ---
  frost_wolf: { id: "frost_wolf", name: "Frost Wolf", level: 18, maxHp: 220, attack: 20, defense: 12, attackSpeed: 3, aggroRange: 6, chaseRange: 12, respawnTicks: 450, xpReward: 110, lootTable: [{ itemId: "gold_coins", quantity: 15, chance: 0.7 }, { itemId: "wolf_pelt", quantity: 1, chance: 0.3 }] },
  ice_wraith: { id: "ice_wraith", name: "Ice Wraith", level: 20, maxHp: 180, attack: 24, defense: 8, attackSpeed: 4, aggroRange: 5, chaseRange: 10, respawnTicks: 500, xpReward: 130, lootTable: [{ itemId: "gold_coins", quantity: 20, chance: 0.8 }, { itemId: "frost_shard", quantity: 1, chance: 0.15 }] },
  yeti: { id: "yeti", name: "Yeti", level: 22, maxHp: 350, attack: 26, defense: 18, attackSpeed: 5, aggroRange: 4, chaseRange: 8, respawnTicks: 600, xpReward: 160, lootTable: [{ itemId: "gold_coins", quantity: 30, chance: 0.9 }, { itemId: "yeti_fur", quantity: 1, chance: 0.2 }] },
  crystal_golem: { id: "crystal_golem", name: "Crystal Golem", level: 25, maxHp: 400, attack: 22, defense: 25, attackSpeed: 6, aggroRange: 3, chaseRange: 6, respawnTicks: 700, xpReward: 200, lootTable: [{ itemId: "gold_coins", quantity: 40, chance: 0.9 }, { itemId: "crystal_core", quantity: 1, chance: 0.1 }] },

  // --- Dragon's Lair Dungeon Mobs ---
  dragonkin: { id: "dragonkin", name: "Dragonkin", level: 24, maxHp: 300, attack: 28, defense: 16, attackSpeed: 4, aggroRange: 5, chaseRange: 15, respawnTicks: 9999, xpReward: 180, lootTable: [{ itemId: "gold_coins", quantity: 35, chance: 0.9 }, { itemId: "dragon_scale", quantity: 1, chance: 0.15 }] },
  elder_drake: {
    id: "elder_drake", name: "Elder Drake", level: 30, maxHp: 1500, attack: 35, defense: 25, attackSpeed: 3, aggroRange: 12, chaseRange: 999, respawnTicks: 9999, xpReward: 1000, isBoss: true,
    bossAbilities: [
      { id: "fire_breath", name: "Fire Breath", damage: 30, radius: 5, cooldownTicks: 60, telegraphTicks: 12 },
      { id: "tail_sweep", name: "Tail Sweep", damage: 25, radius: 3, cooldownTicks: 40, telegraphTicks: 8 },
      { id: "summon_dragonkin", name: "Summon Dragonkin", damage: 0, radius: 0, cooldownTicks: 120, telegraphTicks: 0 },
    ],
    lootTable: [{ itemId: "dragon_slayer", quantity: 1, chance: 0.2 }, { itemId: "drake_plate", quantity: 1, chance: 0.25 }, { itemId: "dragon_scale", quantity: 3, chance: 1.0 }, { itemId: "gold_coins", quantity: 200, chance: 1.0 }],
  },
};
